high5_hospital_doctor_homepage:
    path:     /homepage
    defaults: { _controller: High5HospitalDoctorBundle:Default:index }

high5_hospital_doctor_login:
    path: /login
    defaults: { _controller: High5HospitalDoctorBundle:Default:login }

high5_hospital_doctor_logout:
    path: /logout
    defaults: { _controller: High5HospitalDoctorBundle:Default:logOut }

high5_hospital_doctor_plan_rdv:
    path: /planrdv
    defaults: { _controller: High5HospitalDoctorBundle:Default:planRendezvous }

high5_hospital_doctor_edit_patient_file:
    path: /edit/patientfile
    defaults: { _controller: High5HospitalDoctorBundle:Default:editPatientFile }

high5_hospital_doctor_find_patient_file:
    path: /find/patientfile
    defaults: { _controller: High5HospitalDoctorBundle:Default:findPatientFile }