<?php

namespace Proxies\__CG__\High5\Hospital\DataAccessLayerBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Personne extends \High5\Hospital\DataAccessLayerBundle\Entity\Personne implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'id', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'nom', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'prenom', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'cin', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'adresse', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'telephone', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'classe', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'username', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'mdp', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'isActive', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'fkHopital');
        }

        return array('__isInitialized__', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'id', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'nom', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'prenom', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'cin', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'adresse', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'telephone', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'classe', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'username', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'mdp', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'isActive', '' . "\0" . 'High5\\Hospital\\DataAccessLayerBundle\\Entity\\Personne' . "\0" . 'fkHopital');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Personne $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setCin($cin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCin', array($cin));

        return parent::setCin($cin);
    }

    /**
     * {@inheritDoc}
     */
    public function getCin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCin', array());

        return parent::getCin();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', array($telephone));

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', array());

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setClasse($classe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClasse', array($classe));

        return parent::setClasse($classe);
    }

    /**
     * {@inheritDoc}
     */
    public function getClasse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClasse', array());

        return parent::getClasse();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setMdp($mdp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMdp', array($mdp));

        return parent::setMdp($mdp);
    }

    /**
     * {@inheritDoc}
     */
    public function getMdp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMdp', array());

        return parent::getMdp();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($isActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', array($isActive));

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', array());

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkHopital(\High5\Hospital\DataAccessLayerBundle\Entity\Hopital $fkHopital = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkHopital', array($fkHopital));

        return parent::setFkHopital($fkHopital);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkHopital()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkHopital', array());

        return parent::getFkHopital();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', array());

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', array($serialized));

        return parent::unserialize($serialized);
    }

}
